# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c075c98cb22dae962ac76ca2e8c9b23185691760bbc37d543a5933f8db79e2ddcad940052f90f72574ee9699c4953c019c0b6c26dce6b601cf0db91af76154b

test:
  secret_key_base: dbc1d76ac7ee28c3808e8291775579c96007586a95fc7d671a910772b3941029f97bbe2c84bdb52ba0bdde5e24fddf1045369000ce1d90144e1d61fa9eed41d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
